name: release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract binary from Docker image
        run: |
          container_id=$(docker create ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}:pr-3)
          docker cp $container_id:/usr/bin/cpu_air_prover .
          docker cp $container_id:/usr/bin/cpu_air_verifier .
          docker rm $container_id
          
      - name: Verify file existence#1
        run: pwd

      - name: Verify file existence#2
        run: ls -l

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.4.0
        with:
          file_glob: true
          tag: ${{ github.ref }}
          file: cpu_air*
